ROLE_MANAGER = 'manager'
ROLE_EXECUTOR = 'executor'
ROLE_REVIEWER = 'reviewer'

ROLES_MANAGER_OR_EXECUTOR = {ROLE_MANAGER, ROLE_EXECUTOR}
ROLES_MANAGER_OR_REVIEWER = {ROLE_MANAGER, ROLE_REVIEWER}
ROLES_ALL = {ROLE_MANAGER, ROLE_EXECUTOR, ROLE_REVIEWER}

VALID_ENCODINGS = ['utf-8-sig', 'gbk', 'utf-8']
