# Generated by Django 5.2.14 on 2026-06-05 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('eligible', '可结业'), ('pending_checkin', '待补签'), ('pending_payment', '待缴费'), ('ineligible', '不可结业'), ('graduated', '已结业')], default='ineligible', max_length=20)),
                ('remark', models.TextField(blank=True, default='')),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graduated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_graduations', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to='training.registration')),
            ],
            options={
                'db_table': 'training_graduation',
            },
        ),
    ]
